runtime: python37

handlers:
# Tutorial files.
- url: /static
  static_dir: static
  secure: always

# Favicon.
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  secure: always

# Dynamic content.
- url: /.*
  script: auto
  secure: always
